[package]
name = "bevy_github_ci_template"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.67.0"

[dependencies]
bevy = "0.10"
bevy_rapier2d = {git="https://github.com/ChrisJanssens/bevy_rapier.git"}
